POST http://localhost:8081/api/route-recommendations
Content-Type: application/json

{
  "origin": "SMU",
  "destination": "Orchard MRT",
  "departureTime": "2026-09-18T15:00:00+08:00",
  "preferences": {
    "maxWalkingMinutes": 15,
    "wheelchairAccessible": false,
    "minimizeTransfers": true
  }
}

###
GET http://localhost:8081/api/lta/bus-routes?skip=0

###
GET http://localhost:8081/api/lta/bus-services?skip=0

###
GET http://localhost:8081/api/lta/station-crowding?trainLine=DTL

###
GET http://localhost:8081/api/lta/facilities-maintenance

###
GET http://localhost:8081/api/lta/train-alerts